src/containers/CourseCard/__snapshots__/index.test.jsx.snap, src/containers/CourseCard/components/Banners/CertificateBanner.jsx, src/containers/CourseCard/components/Banners/CourseBanner.jsx, src/containers/CourseCard/components/CourseCardActions/__snapshots__/index.test.jsx.snap, src/containers/CourseCard/components/CourseCardActions/index.jsx, src/containers/CourseCard/components/RelatedProgramsBadge.jsx, src/containers/CourseCard/components/RelatedProgramsBadge/__snapshots__/index.test.jsx.snap, src/containers/CourseCard/components/RelatedProgramsBadge/hooks.jsx, src/containers/CourseCard/components/RelatedProgramsBadge/hooks.test.js, src/containers/CourseCard/components/RelatedProgramsBadge/index.jsx, src/containers/CourseCard/components/RelatedProgramsBadge/index.test.jsx, src/containers/CourseCard/components/RelatedProgramsBadge/messages.js, src/containers/CourseCard/index.jsx, src/containers/RelatedProgramsModal/__snapshots__/index.test.jsx.snap, src/containers/RelatedProgramsModal/index.jsx, src/data/constants/requests.js, src/data/redux/cardData/selectors.js, src/data/redux/thunkActions/app.js, src/data/redux/thunkActions/requests.js, src/data/services/lms/api.js, src/data/services/lms/fakeData/courses.js, src/data/services/lms/fakeData/testUtils.js, src/test/app.test.jsx, src/test/inspector.js, src/test/messages.js
Adds initial integration tests, as well as unit tests for Related Programs Badge.
Includes test hook for messages with passed values.
=> Chore: integration tests and programs badge tests

src/containers/CourseCard/components/Banners/CertificateBanner.jsx, src/containers/CourseCard/components/CourseCardDetails/hooks.js, src/containers/CourseCard/components/CourseCardDetails/hooks.test.js, src/containers/CourseCard/components/CourseCardDetails/messages.js, src/data/redux/app/selectors.js, src/data/services/lms/fakeData/courses.js, src/test/app.test.jsx
Removes estimated duration for programs from UI and data
Removes Certificate Download workflow and data
Add StartDate to course details and data
JIRA:
[AU-799](https://2u-internal.atlassian.net/browse/AU-799)
[AU-802](https://2u-internal.atlassian.net/browse/AU-802)
[AU-821](https://2u-internal.atlassian.net/browse/AU-821)
=> feat: data model updates

src/containers/CourseCard/components/CourseCardBanners/CertificateBanner.test.jsx, src/containers/CourseCard/components/CourseCardBanners/__snapshots__/CertificateBanner.test.jsx.snap, src/containers/CourseCard/components/RelatedProgramsBadge/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/GreetingBanner.jsx, src/containers/LearnerDashboardHeader/index.jsx, src/containers/MasqueradeBar/__snapshots__/index.test.jsx.snap, src/containers/MasqueradeBar/hooks.js, src/containers/MasqueradeBar/hooks.test.js, src/containers/MasqueradeBar/index.jsx, src/containers/MasqueradeBar/index.scss, src/containers/MasqueradeBar/index.test.jsx, src/containers/MasqueradeBar/messages.js, src/containers/RelatedProgramsModal/components/__snapshots__/ProgramCard.test.jsx.snap, src/data/constants/requests.js, src/data/redux/hooks.js, src/data/redux/requests/reducer.js, src/data/redux/requests/selectors.js, src/data/redux/requests/selectors.test.js, src/data/redux/thunkActions/app.js, src/data/redux/thunkActions/requests.js, src/data/services/lms/api.js, src/setupTest.jsx
https://user-images.githubusercontent.com/83240113/191574872-e0a22fcf-90b8-4b01-b2d4-4b0da805b639.mov
=> Leangseu edx/masquerade user

src/containers/CourseFilterControls/CourseFilterControls.jsx, src/containers/CourseFilterControls/__snapshots__/CourseFilterControls.test.jsx.snap, src/containers/CourseList/__snapshots__/index.test.jsx.snap, src/containers/CourseList/hooks.js, src/containers/CourseList/hooks.test.js, src/containers/CourseList/index.jsx, src/containers/CourseList/index.scss, src/containers/CourseList/index.test.jsx, src/containers/Dashboard/__snapshots__/index.test.jsx.snap, src/containers/Dashboard/index.jsx, src/containers/Dashboard/index.test.jsx, src/containers/MasqueradeBar/__snapshots__/index.test.jsx.snap, src/containers/MasqueradeBar/hooks.js, src/containers/MasqueradeBar/hooks.test.js, src/containers/MasqueradeBar/index.jsx, src/containers/MasqueradeBar/index.test.jsx, src/data/redux/hooks.js, src/data/redux/requests/selectors.js, src/data/redux/requests/selectors.test.js
=> masquerade stateful button and initial loading page

src/data/services/lms/api.js, src/data/services/lms/api.test.js, src/data/services/lms/constants.js
adds unit tests for lms api methods.
=> feat: lms api unit tests

package.json, src/containers/CourseCard/components/CourseCardBanners/CourseBanner.jsx, src/containers/CourseCard/components/CourseCardBanners/CourseBanner.test.jsx, src/containers/CourseCard/components/CourseCardBanners/__snapshots__/CourseBanner.test.jsx.snap, src/containers/CourseCard/components/CourseCardDetails/__snapshots__/index.test.jsx.snap, src/containers/CourseCard/components/CourseCardDetails/hooks.js, src/containers/CourseCard/components/CourseCardDetails/hooks.test.js, src/containers/CourseCard/components/CourseCardDetails/index.jsx, src/containers/CourseCard/components/CourseCardDetails/index.test.jsx, src/data/redux/app/selectors.js
=> fix: access expire date should hide on null

src/containers/UnenrollConfirmModal/components/ReasonPane.test.jsx, src/containers/UnenrollConfirmModal/hooks.js, src/containers/UnenrollConfirmModal/hooks.test.js, src/containers/UnenrollConfirmModal/index.jsx, src/containers/UnenrollConfirmModal/index.test.jsx, src/data/redux/thunkActions/app.js, src/data/services/lms/api.js, src/data/services/lms/api.test.js, src/data/services/lms/utils.js, src/data/services/lms/utils.test.js
the request body to django need to be convert into `course_id=some_course&enrollment_type=unenroll`.
=> fix: update logic for unenrollment

.env.development, .env.test
change local port to 1996 to make local `edx-platform` redirect correctly
=> chore: update local port

src/data/services/lms/urls.js, src/data/services/lms/urls.test.js
TLDR; fix for broken application when the url is null.
=> fix: add handler when url is null

package-lock.json, package.json
Downgrade `frontend-platform` to corresponds to footer override peer dependencies.
=> fix: footer and frontend-platform peer deps

src/data/redux/thunkActions/app.js, src/data/redux/thunkActions/app.test.js
currently, change session work but the user has to refresh the page because race condition. This pr is added to solve that.
=> chore: make sure to load initialize after change session

src/containers/CourseCard/components/CourseCardActions/UpgradeButton.jsx, src/containers/CourseCard/components/CourseCardActions/UpgradeButton.test.jsx, src/containers/CourseCard/components/CourseCardActions/__snapshots__/UpgradeButton.test.jsx.snap, src/containers/CourseCard/components/CourseCardActions/hooks.js, src/containers/CourseCard/components/CourseCardActions/hooks.test.js, src/data/redux/hooks.js, src/data/services/segment/constants.js, src/widgets/LookingForChallengeWidget/__snapshots__/index.test.jsx.snap, src/widgets/LookingForChallengeWidget/index.jsx, src/widgets/LookingForChallengeWidget/index.test.jsx, src/widgets/RecommendationsPanel/LoadedView.jsx, src/widgets/RecommendationsPanel/LoadedView.test.jsx, src/widgets/RecommendationsPanel/__snapshots__/LoadedView.test.jsx.snap, src/widgets/RecommendationsPanel/hooks.js, src/widgets/RecommendationsPanel/hooks.test.js, src/widgets/RecommendationsPanel/index.jsx, src/widgets/RecommendationsPanel/index.test.jsx
- add tracking for upgrade button
- add tracking for search button click
=> feat: tracking upgrade and discovery

src/widgets/RecommendationsPanel/LoadedView.jsx, src/widgets/RecommendationsPanel/LoadedView.test.jsx, src/widgets/RecommendationsPanel/__snapshots__/LoadedView.test.jsx.snap, src/widgets/RecommendationsPanel/components/CourseCard.jsx, src/widgets/RecommendationsPanel/hooks.js, src/widgets/RecommendationsPanel/index.jsx, src/widgets/RecommendationsPanel/index.test.jsx, src/widgets/RecommendationsPanel/messages.js
ticket: https://2u-internal.atlassian.net/browse/VAN-1158
=> fix: show Popular on edX title for general recs [VAN-1158]

src/containers/CourseCard/components/CourseCardImage.jsx, src/widgets/LookingForChallengeWidget/__snapshots__/index.test.jsx.snap
=> fix: image wrapper

src/App.jsx, src/tracking/trackers/entitlements.js, src/tracking/trackers/entitlements.test.js
=> fix: tracking for entitlement

src/containers/CourseCard/components/CourseCardMenu/__snapshots__/index.test.jsx.snap, src/containers/CourseCard/components/CourseCardMenu/index.jsx, src/containers/CourseCard/components/CourseCardMenu/index.test.jsx
Reverts edx/frontend-app-learner-dashboard#88 reverting one more for stage still broken
=> Revert "chore: add facebook button back"

src/containers/LearnerDashboardHeader/AuthenticatedUserDropdown.jsx, src/containers/LearnerDashboardHeader/AuthenticatedUserDropdown.test.jsx, src/containers/LearnerDashboardHeader/__snapshots__/AuthenticatedUserDropdown.test.jsx.snap, src/containers/LearnerDashboardHeader/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/hooks.js, src/containers/LearnerDashboardHeader/hooks.test.js, src/containers/LearnerDashboardHeader/index.jsx, src/containers/LearnerDashboardHeader/index.test.jsx, src/containers/LearnerDashboardHeader/messages.js, src/tracking/constants.js, src/tracking/index.js, src/tracking/trackers/findCourses.js, src/tracking/trackers/findCourses.test.js, src/widgets/LookingForChallengeWidget/__snapshots__/index.test.jsx.snap, src/widgets/LookingForChallengeWidget/index.jsx, src/widgets/LookingForChallengeWidget/index.test.jsx, src/widgets/RecommendationsPanel/LoadedView.jsx, src/widgets/RecommendationsPanel/LoadedView.test.jsx, src/widgets/RecommendationsPanel/__snapshots__/LoadedView.test.jsx.snap, src/widgets/RecommendationsPanel/track.js
=> feat: add explore course link on the header

src/containers/LearnerDashboardHeader/AuthenticatedUserDropdown.jsx, src/containers/LearnerDashboardHeader/__snapshots__/AuthenticatedUserDropdown.test.jsx.snap
=> chore: fix overlap explore course button

src/containers/CourseList/hooks.js, src/containers/CourseList/hooks.test.js, src/data/constants/app.js, src/data/redux/app/selectors/currentList.js, src/data/redux/app/selectors/currentList.test.js
ticket: https://2u-internal.atlassian.net/browse/AU-1024
What change:
- page size default to 25
- if the url include `disable_pagination=1`, it will disable pagination
=> feat: pagination to 25 and allow disable_pagination

src/widgets/RecommendationsPanel/track.js
[VAN-1261](https://2u-internal.atlassian.net/browse/VAN-1261)
=> feat: add page property to recommendations click event

src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/EligibleContent.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/EligibleContent.test.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/PendingContent.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/PendingContent.test.jsx, src/data/services/lms/api.js, src/data/services/lms/api.test.js, src/tracking/trackers/credit.js, src/tracking/trackers/credit.test.js
fix credit banner link. The changes are explained in the comment.
=> fix: credit banner link

src/containers/LearnerDashboardHeaderVariant/ExpandedHeader/AuthenticatedUserDropdown.jsx, src/containers/LearnerDashboardHeaderVariant/ExpandedHeader/__snapshots__/AuthenticatedUserDropdown.test.jsx.snap
Follow-up from #119 , add the updated links to the variant header which we are now using.
=> fix: update menu item link for variant header

src/containers/CourseCard/components/CourseCardActions/BeginCourseButton.jsx, src/containers/CourseCard/components/CourseCardActions/BeginCourseButton.test.jsx
- Disable begin button when audit expire
=> fix: begin button disable when audit access expire

src/containers/CourseCard/components/CourseCardTitle.jsx, src/containers/CourseCard/components/CourseCardTitle.test.jsx, src/containers/CourseCard/components/__snapshots__/CourseCardTitle.test.jsx.snap
TLDR; `<a />` tag disable isn't working. Need to make on clickable disable manually.
=> fix: disable title link on homeUrl undefined

src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/ApprovedContent.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/ApprovedContent.test.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/MustRequestContent.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/MustRequestContent.test.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/PendingContent.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/PendingContent.test.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/components/CreditContent.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/components/CreditContent.test.jsx, src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/components/__snapshots__/CreditContent.test.jsx.snap
disable credit action while masquerading.
https://2u-internal.atlassian.net/browse/AU-1091
=> fix: make credit actions disable on masquerade

src/components/ZendeskFab/__snapshots__/index.test.jsx.snap, src/components/ZendeskFab/index.jsx
constraint chat department so the support can allocate the resource better.
https://2u-internal.atlassian.net/browse/AU-1201
=> chore: update zendesk chat department

src/containers/CourseCard/components/CourseCardActions/BeginCourseButton.jsx, src/containers/CourseCard/components/CourseCardActions/BeginCourseButton.test.jsx, src/containers/CourseCard/components/CourseCardActions/ResumeButton.jsx, src/containers/CourseCard/components/CourseCardActions/ResumeButton.test.jsx, src/containers/CourseCard/components/CourseCardActions/SelectSessionButton.jsx, src/containers/CourseCard/components/CourseCardActions/SelectSessionButton.test.jsx, src/containers/CourseCard/components/CourseCardActions/UpgradeButton.jsx, src/containers/CourseCard/components/CourseCardActions/UpgradeButton.test.jsx, src/containers/CourseCard/components/CourseCardActions/ViewCourseButton.jsx, src/containers/CourseCard/components/CourseCardActions/ViewCourseButton.test.jsx, src/containers/CourseCard/components/CourseCardActions/__snapshots__/SelectSessionButton.test.jsx.snap, src/containers/CourseCard/components/CourseCardActions/__snapshots__/UpgradeButton.test.jsx.snap, src/containers/CourseCard/components/CourseCardActions/__snapshots__/ViewCourseButton.test.jsx.snap, src/containers/CourseCard/components/CourseCardDetails/hooks.test.js, src/containers/CourseCard/components/CourseCardImage.jsx, src/containers/CourseCard/components/CourseCardImage.test.jsx, src/containers/CourseCard/components/CourseCardTitle.jsx, src/containers/CourseCard/components/CourseCardTitle.test.jsx, src/containers/CourseCard/components/__snapshots__/CourseCardImage.test.jsx.snap, src/containers/CourseCard/components/__snapshots__/CourseCardTitle.test.jsx.snap, src/containers/CourseCard/components/hooks.js, src/containers/CourseCard/components/hooks.test.js
- refactor disable course action into a single hook file
- make sure when course view button disabled, course title and course image should be disable too
https://2u-internal.atlassian.net/browse/AU-1169
=> chore: refactor disable course action into a single hook

src/containers/CourseCard/components/CourseCardMenu/__snapshots__/index.test.jsx.snap, src/containers/CourseCard/components/CourseCardMenu/index.jsx
Show the unenrollment button for executive education courses
JIRA -> [ENT-7524](https://2u-internal.atlassian.net/browse/ENT-7524)
=> feat: show unenrollment button for executive education courses

src/components/ModalView/index.jsx, src/components/ModalView/index.scss
Description:
We have stacked the buttons of modal window on small screens.
It has been tested locally 
[Jira Ticket]([VAN-1601](https://2u-internal.atlassian.net/browse/VAN-1601))
Screenshot:
=> Ahtesham/van 1601/stack buttons

public/index.html, src/App.jsx, src/App.test.jsx, src/RecsPaintedDoorExpContext.jsx, src/__snapshots__/App.test.jsx.snap, src/components/ModalView/__snapshots__/index.test.jsx.snap, src/components/ModalView/index.jsx, src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx, src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.test.jsx, src/containers/LearnerDashboardHeader/CollapsedHeader/__snapshots__/CollapseMenuBody.test.jsx.snap, src/containers/LearnerDashboardHeader/CollapsedHeader/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/CollapsedHeader/index.jsx, src/containers/LearnerDashboardHeader/CollapsedHeader/index.test.jsx, src/containers/LearnerDashboardHeader/ExpandedHeader/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx, src/widgets/LookingForChallengeWidget/index.jsx, src/widgets/LookingForChallengeWidget/index.test.jsx, src/widgets/RecommendationsPanel/LoadedView.jsx, src/widgets/RecommendationsPanel/LoadedView.test.jsx, src/widgets/RecommendationsPanel/__snapshots__/LoadedView.test.jsx.snap, src/widgets/RecommendationsPanel/index.jsx, src/widgets/RecommendationsPanel/recsPaintedDoorExpTrack.js, src/widgets/RecommendationsPanel/track.js
VAN-1604
**Description:**
- Setup painted door optimizely experiment
- Add eventing to painted door experiment
=> feat: add experiment and eventing to recommendations painted door exp

src/widgets/ProductRecommendations/api.js, src/widgets/RecommendationsPanel/api.js
Point cross product recommendations url from learner_recommendations to edx-recommendations plugin.
VAN-1596
=> fix: update dashboard recommendations url

src/widgets/RecommendationsPaintedDoorBtn/track.js, src/widgets/RecommendationsPaintedDoorBtn/track.test.js, src/widgets/RecommendationsPanel/components/index.scss
- Fixed recommendations card design
- Fixed eventing issue with recommendations painted door experiment
**Recommendations Panel Before:**
**Recommendations Panel After:**
=> fix: recommendations card design and painted door eventing

src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx, src/containers/LearnerDashboardHeader/ExpandedHeader/AuthenticatedUserDropdown.jsx, src/containers/LearnerDashboardHeader/ExpandedHeader/__snapshots__/AuthenticatedUserDropdown.test.jsx.snap, src/containers/LearnerDashboardHeader/messages.js
Reverts openedx/frontend-app-learner-dashboard#206
=> Revert "feat: Update header user dropdown back to Order History"

package-lock.json, package.json, src/containers/WidgetContainers/LoadedSidebar/__snapshots__/index.test.jsx.snap, src/containers/WidgetContainers/LoadedSidebar/index.jsx
This will increase the size of the plugin slot to allow for a full view of the Profile Plugin.
=> fix: increase plugin slot window

package-lock.json, package.json
This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.4`.
=> chore: bump frontend-platform (#216)

src/ExperimentContext.test.jsx, src/containers/CourseCard/components/CourseCardBanners/RelatedProgramsBanner/index.jsx, src/containers/CourseCard/components/RelatedProgramsBadge/index.jsx, src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx, src/containers/LearnerDashboardHeader/CollapsedHeader/__snapshots__/CollapseMenuBody.test.jsx.snap, src/containers/LearnerDashboardHeader/ConfirmEmailBanner/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/ConfirmEmailBanner/messages.js, src/containers/LearnerDashboardHeader/ExpandedHeader/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx, src/i18n/messages/pt_BR.json, src/i18n/messages/zh_CN.json, src/widgets/ProductRecommendations/index.test.jsx
https://2u-internal.atlassian.net/browse/AU-1574
=> fix: a few typos

.github/CODEOWNERS
*  transition ownership of the component
*  correct ownership label for vanguards
FIXES: APER-3174
=> feat: transition ownership of the  learner dash

src/containers/CoursesPanel/__snapshots__/index.test.jsx.snap, src/containers/CoursesPanel/index.jsx, src/containers/CoursesPanel/index.test.jsx
*  this creates a plug-in slot with an ID for each of no courses and course list
FIXES: APER-3304
=> feat:  separate no courses and course list into slots

.github/workflows/ci.yml, package-lock.json, package.json
Includes changes from:
#318 - add logging for GH action
#320 - upgrade to Paragon v22
=> Merge latest from master to 2u/main

src/containers/LearnerDashboardHeader/ConfirmEmailBanner/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/ConfirmEmailBanner/messages.js
Remove edx-Specific reference from email confirmation banner.
=> fix: Remove edX-specific reference

.github/workflows/ci.yml, package-lock.json, package.json, src/containers/LearnerDashboardHeader/ConfirmEmailBanner/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/ConfirmEmailBanner/messages.js
=> update 2u/main from master

package-lock.json, package.json
Includes minor dependency updates
=> Update 2u/main with latest master branch

src/config/index.js
Adds the `SEARCH_CATALOG_URL` environment variable to the merge config operation
=> chore: update merge config

package-lock.json, package.json
removing an unnecessary import
FIXES: APER-3600
=> chore: removing an unnecessary import

src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx, src/containers/LearnerDashboardHeader/__snapshots__/index.test.jsx.snap, src/containers/LearnerDashboardHeader/hooks.js, src/containers/LearnerDashboardHeader/hooks.test.js, src/containers/LearnerDashboardHeader/index.test.jsx, src/data/services/lms/api.js, src/data/services/lms/urls.js, src/hooks/api.js, src/hooks/api.test.js
=> chore: merge 2u/main with master branch
