- src/containers/EmptyCourse/SuggestedCourses/__snapshots__/index.test.jsx.snap
- src/containers/EmptyCourse/SuggestedCourses/index.jsx
- src/containers/EmptyCourse/SuggestedCourses/index.test.jsx
- src/containers/EmptyCourse/SuggestedCourses/messages.js
- src/containers/EmptyCourse/__snapshots__/index.test.jsx.snap
- src/containers/EmptyCourse/components/ExampleCoursesWidget/index.jsx
- src/containers/EmptyCourse/index.jsx
- src/containers/EmptyCourse/index.scss
- src/containers/EmptyCourse/index.test.jsx
- src/data/redux/app/reducer.js
- src/data/redux/app/selectors.js
- src/data/redux/hooks.js
- src/data/services/lms/fakeData/courses.js
> feat: empty course and suggested courses

- src/containers/WidgetSidebar/index.scss
[AU-754](https://2u-internal.atlassian.net/browse/AU-754)
> chore: update side widget style

- src/App.scss
- src/containers/CourseCard/components/Banners/EntitlementBanner.jsx
- src/containers/CourseCard/components/Banners/EntitlementBanner.test.jsx
- src/containers/CourseCard/components/Banners/__snapshots__/EntitlementBanner.test.jsx.snap
- src/containers/CourseCard/components/CourseCardActions/hooks.js
- src/containers/CourseCard/components/CourseCardActions/hooks.test.js
- src/containers/CourseCard/components/CourseCardDetails/hooks.js
- src/containers/CourseCard/components/CourseCardDetails/hooks.test.js
- src/containers/CourseCard/components/CourseCardDetails/index.jsx
- src/containers/CourseFilterControls/ActiveCourseFilters.jsx
- src/containers/CourseFilterControls/components/FilterForm.jsx
- src/containers/Dashboard/index.jsx
- src/containers/SelectSessionModal/__snapshots__/index.test.jsx.snap
- src/containers/SelectSessionModal/index.jsx
- src/containers/SelectSessionModal/index.test.jsx
- src/data/constants/app.js
- src/data/redux/app/selectors.js
- src/data/redux/hooks.js
- src/data/services/lms/fakeData/courses.js
> fix: filter by not-enrolled was reversed

- src/containers/CourseCard/CourseCard.scss
- src/containers/CourseCard/__snapshots__/index.test.jsx.snap
- src/containers/CourseCard/index.jsx
> fix: course card banner radius

- src/App.scss
> chore: make banner icon dark

- src/containers/CourseCard/CourseCard.scss
- src/containers/CourseCard/components/CourseCardBanners/CourseBanner.jsx
- src/containers/CourseCard/components/CourseCardBanners/CourseBanner.test.jsx
- src/containers/CourseCard/components/CourseCardBanners/__snapshots__/CourseBanner.test.jsx.snap
- src/containers/CourseCard/components/CourseCardBanners/messages.js
- src/data/redux/app/selectors.js
- feat: add has access split
- chore: rename hasAccess to coursewareAccess
https://github.com/openedx/edx-platform/pull/30981
> leangseu edx/has access split

- src/App.jsx
- src/containers/CourseCard/components/RelatedProgramsBadge/index.jsx
- src/containers/CourseList/index.jsx
- src/containers/WidgetSidebar/index.jsx
- src/containers/WidgetSidebar/index.scss
- src/containers/WidgetSidebar/messages.js
Adds margins to Course List title, show widget bar at small size, and fixes widget card text/icon
Also fixes related programs badge spacing and adds method for loading mock data in window.
`window.loadMockData()` will load the full set of test data into the env.
https://docs.google.com/document/d/1tBesg2CuIGeIZJ3Gvk9BFrQfyT3DjJLCU53g3181NAQ/edit#
> fix: header spacing and widget text

- package-lock.json
- package.json
- src/App.jsx
- src/__snapshots__/App.test.jsx.snap
- src/containers/CourseCard/components/CourseCardContent.jsx
- src/containers/CourseCard/components/CourseCardMenu/__snapshots__/index.test.jsx.snap
- src/containers/CourseCard/components/CourseCardMenu/index.jsx
- src/containers/CourseCard/components/__snapshots__/CourseCardContent.test.jsx.snap
- src/containers/CourseList/__snapshots__/index.test.jsx.snap
- src/containers/CourseList/hooks.js
- src/containers/CourseList/hooks.test.js
- src/containers/CourseList/index.jsx
- src/containers/CourseList/index.test.jsx
- src/containers/Dashboard/__snapshots__/index.test.jsx.snap
- src/containers/Dashboard/index.jsx
- src/containers/Dashboard/index.test.jsx
- src/containers/LearnerDashboardHeader/GreetingBanner.jsx
- src/containers/LearnerDashboardHeader/__snapshots__/GreetingBanner.test.jsx.snap
- src/containers/RelatedProgramsModal/__snapshots__/index.test.jsx.snap
- src/containers/RelatedProgramsModal/components/ProgramCard.jsx
- src/containers/RelatedProgramsModal/components/__snapshots__/ProgramCard.test.jsx.snap
- src/containers/RelatedProgramsModal/components/messages.js
- src/containers/RelatedProgramsModal/index.jsx
- src/messages.js
Fixes for Jeff's a11y issues:
```
The edX logo doesn’t have the (typical?) wrapper link pointing to https://edx.org/. Will that pattern be repeated elsewhere?
“Good morning” has an <h5>. Please don’t use an <h> element for this, or give it role=“presentation”, which means “I’m a div, not what it appears”.
There’s no SkipNav link, which might be appropriate, given that the the header is minimal number of tab stops and atypical. But my recommendation here depends on the first question.
There’s no <h1>.  Could you add one with class=“sr-only”?  How about <h1 class=“sr-only”>Learner Dashboard</h1>
The page title should typically match the H1 (not a strict requirement), or reflect any changes to the H1. If you intend to use “Learner dashboard” and “Dashboard” to reflect the two dashboards that …
```
> fix: a11y issues

- src/containers/CourseCard/components/CourseCardActions/SelectSessionButton.jsx
- src/containers/CourseCard/components/CourseCardActions/__snapshots__/SelectSessionButton.test.jsx.snap
Fix button label for "Select Entitlements" modal. Should be "Select Session" instead of "Resume".
> chore: fix typo for selection button

- Makefile
The Transifex cli started requiring the -t or --translations flag in the pull command in order to fetch translations.
https://github.com/transifex/cli/pull/96
> fix: update transfex flag for tx cli 1.4.0

- src/App.jsx
- src/App.test.jsx
- src/__snapshots__/App.test.jsx.snap
- src/containers/CourseCard/components/CourseCardActions/ViewCourseButton.jsx
- src/containers/CourseCard/components/CourseCardActions/ViewCourseButton.test.jsx
- src/containers/CourseCard/components/CourseCardActions/__snapshots__/ViewCourseButton.test.jsx.snap
- src/containers/CourseCard/components/CourseCardBanners/CertificateBanner.jsx
- src/containers/CourseCard/components/CourseCardBanners/CourseBanner.jsx
- src/containers/CourseCard/components/CourseCardBanners/EntitlementBanner.jsx
- src/containers/CourseCard/components/CourseCardDetails/hooks.js
- src/containers/CourseCard/components/CourseCardMenu/__snapshots__/index.test.jsx.snap
- src/containers/CourseCard/components/CourseCardMenu/index.jsx
- src/containers/CourseCard/components/CourseCardMenu/index.test.jsx
- src/containers/CourseList/hooks.test.js
- src/containers/Dashboard/index.jsx
- src/containers/Dashboard/index.test.jsx
- src/containers/UnenrollConfirmModal/hooks.js
- src/containers/UnenrollConfirmModal/hooks.test.js
- src/data/redux/app/selectors/courseCard.js
- src/data/redux/app/selectors/courseCard.test.js
- src/data/redux/hooks.js
- src/data/services/lms/urls.js
- src/messages.js
- src/setupTest.jsx
- src/test/app.test.jsx
- src/utils/dateFormatter.js
- src/utils/hooks.js
Fixes cert preview url
Only show expiration warning for entitlements if not fulfilled.
hide unenroll option on unfulfilled entitlements
fix unenroll when reason is skipped.
better-internationalize dates
enable View Course button for expired entitlements
provides error page on initialize or refreshList failure
(From Leangseu) - fixes implied relative urls
> fix: Bug-doc fixes

- src/data/redux/thunkActions/app.js
- src/data/redux/thunkActions/app.test.js
- src/data/redux/thunkActions/requests.js
- src/data/redux/thunkActions/requests.test.js
- src/data/services/lms/api.js
- src/data/services/lms/api.test.js
- src/data/services/lms/constants.js
what change:
- post `${api}/entitlements/v1/entitlements/${uuid}/enrollments` expect a body instead of params and it must include `course_run_id`
- delete `${api}/entitlements/v1/entitlements/${uuid}/enrollments` expect a params of `is_refund`.
The existing bff file for this `api` is in `common/djangoapps/entitlements/rest_api/v1/views.py::EntitlementEnrollmentViewSet`
> fix: select and leave session to match the backend

- src/containers/Dashboard/index.scss
This PR fixes the vertical alignment issue between the enrolled courses section and recommended courses section when the number of enrolled courses is either 1 or 2. 
**Expected Figma Design:**
**Before:**
with 1 enrolled course:
with 2 enrolled courses:
**After:**
with 1 enrolled course:
with 2 enrolled courses:
> fix: alignment issue between enrolled and recommended courses section

- src/containers/SelectSessionModal/hooks.test.js
- src/containers/UnenrollConfirmModal/components/ReasonPane.jsx
- src/containers/UnenrollConfirmModal/components/ReasonPane.test.jsx
- src/containers/UnenrollConfirmModal/components/__snapshots__/ReasonPane.test.jsx.snap
- src/containers/UnenrollConfirmModal/hooks/reasons.js
- src/containers/UnenrollConfirmModal/hooks/reasons.test.js
Prevents "submit" action on unenroll reason form if no reason is provided.
> fix: disable reason select if no reason selected

- src/hooks/api.js
- src/hooks/api.test.js
What get fix:
- Masquerade
- Update entitlement
- update email settings
What change:
- let `action` function take arguments
Why:
- too many functional pointer made react think dispatch was being call outside of the component body
- not the fault on our part of the code, it is the functional hell moment
> fix: update hooks action to take arguments

- src/containers/CourseFilterControls/ActiveCourseFilters.jsx
- src/containers/CourseFilterControls/CourseFilterControls.jsx
- src/containers/CourseFilterControls/__snapshots__/ActiveCourseFilters.test.jsx.snap
- src/containers/CourseFilterControls/hooks.js
- src/containers/CourseFilterControls/hooks.test.js
- src/tracking/constants.js
- src/tracking/index.js
- src/tracking/trackers/filter.js
- src/tracking/trackers/filter.test.js
Ticket: https://2u-internal.atlassian.net/browse/AU-1042
What changed:
- add event to filtering when the refine button click and the filter menu close
- on refine button click the event name will be 
```js
analytics.track('course-dashboard.filter.clicked', {
app_name: 'learner-home',
category: 'filter'
});
```
- on filter close the event will be
```js
analytics.track('course-dashboard.filter_option.selected', {
app_name: 'learner-home',
category: 'filter',
filters: [
'done',
'notStarted'
]
});
```
How to test:
- You need access to segment and edx-internal
1. Add `SEGMENT_KEY` from `edx-internal` to `.env.development` file
2. Restart or run applicaiton `npm start`
3. Click on refine button and close it.
4. You should see event like above in segment learner home live debug
Goal:
1. …
> feat: add event for filtering

- src/containers/CourseCard/components/CourseCardBanners/RelatedProgramsBanner/__snapshots__/index.test.jsx.snap
- src/containers/CourseCard/components/CourseCardBanners/RelatedProgramsBanner/index.jsx
What changed:
- make `related program` text bold.
From this:
To this:
> chore: make related program folder bolder

- src/containers/CourseCard/components/CourseCardBanners/CertificateBanner.jsx
- src/containers/CourseCard/components/CourseCardBanners/CourseBanner.jsx
- src/containers/CourseCard/components/CourseCardBanners/__snapshots__/CertificateBanner.test.jsx.snap
- src/containers/CourseCard/components/CourseCardBanners/__snapshots__/CourseBanner.test.jsx.snap
- src/containers/CourseCard/components/CourseCardImage.jsx
- src/containers/MasqueradeBar/__snapshots__/index.test.jsx.snap
- src/containers/MasqueradeBar/index.jsx
https://2u-internal.atlassian.net/browse/AU-1071
What changed:
- Make inline link has underline
- add aria for masquerade
- remove focus on course thumbnail because it redundant for screen reader
> Improve accessibility for learner home

- .github/workflows/ci.yml
- Makefile
- package-lock.json
- package.json
- src/containers/SelectSessionModal/__snapshots__/index.test.jsx.snap
Ticket
[Migrate from Coveralls to Codecov ](https://github.com/openedx/frontend-wg/issues/9)
**What has changed?**
- Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3
This PR moves the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov 
- Remove unused unnecessary is-5 check
> Migrate from Coveralls to Codecov and removed is5

- src/containers/CourseCard/components/CourseCardActions/ViewCourseButton.jsx
- src/containers/CourseCard/components/CourseCardActions/ViewCourseButton.test.jsx
Ticket: https://2u-internal.atlassian.net/browse/AU-1066
what change:
- disable view button on audit expired access
- disable link is no clickable and lead to undefined page
> fix: disable view button on expired access

- src/data/services/lms/urls.js
Why this caused the error?
- the correct url ended with `/`
- lms try to redirect the incorrect to end with `/`
- cloudflare block the redirect and throw a CORS error.
This may be a one time thing, but we might need to review our cloudflare rewrite policy for this.
> fix: credit cors error

- src/widgets/RecommendationsPanel/api.js
Point API call to a new endpoint.
We are refactoring our recommendation code to reduce redundancy. We moved our recommendation API from `learner_home` and `learner_dashboard` to `learner_recommendations` that's why we need to point API call on a new endpoint.
**Backend PR:**
https://github.com/openedx/edx-platform/pull/31975
After deploying this, we will remove the legacy [code](https://github.com/openedx/edx-platform/pull/31990) from the platform.
[Ticket](https://2u-internal.atlassian.net/jira/software/c/projects/VAN/boards/659?modal=detail&selectedIssue=VAN-1310)
> refactor: update API endpoint

- src/components/NoticesWrapper/hooks.js
- src/components/NoticesWrapper/hooks.test.js
the response from the notices api is
`{data: {results: [a, b, c]} }`
but we were trying to read
`{results: [a, b, c]}`
fix
> fix: noticeswrapper api response error

- package.json
- src/containers/EnterpriseDashboardModal/__snapshots__/index.test.jsx.snap
- src/containers/EnterpriseDashboardModal/messages.js
- src/containers/LearnerDashboardHeaderVariant/BrandLogo.jsx
- src/data/redux/app/selectors/appSelectors.js
- src/data/redux/app/selectors/appSelectors.test.js
The following modal appears for enterprise learners in the B2C learner dashboard. It intends to inform/communicate to enterprise learners that they have an enterprise-specific, branded dashboard page available to them:
However, currently, the MFE assumes if you are an enterprise learner, you should be seeing the modal which is not true. The modal should only show for learners associated with an enterprise that has `enable_learner_portal=True`.
Related PR(s):
* https://github.com/openedx/edx-platform/pull/32142
> fix: account for `isLearnerPortalEnabled` when determining `hasAvailableDashboards`

- Makefile
- package-lock.json
- package.json
- src/i18n/index.js
- src/index.jsx
- src/index.test.jsx
- Bump frontend-platform to bring intl-imports.js script
- Move all i18n imports into `src/i18n/index.js` so intl-imports.js can override it with latest translations
- Add `atlas` into `make pull_translations` when `OPENEDX_ATLAS_PULL` environment variable is set.
Testing
-------
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).
Check the links above for full information about the overall project. …
> feat: use `atlas` in `make pull_translations`

- src/containers/CourseCard/components/CourseCardImage.jsx
- src/containers/CourseCard/components/__snapshots__/CourseCardImage.test.jsx.snap
`Card.Img` expect `.show` from `paragon@20.28.4` onward, specially this pr https://github.com/openedx/paragon/pull/1994. Since course image is using custom css + paragon card img to include verify ribbon and disable/clickable function, this change was an edge case we didn't expect.
> fix: missing image

- src/containers/CourseCard/components/CourseCardMenu/__snapshots__/index.test.jsx.snap
- src/containers/CourseCard/components/CourseCardMenu/index.jsx
- src/containers/CourseCard/components/CourseCardMenu/index.test.jsx
- src/data/redux/app/selectors/courseCard.js
What changed?
- Add `isEarned` back to certificate selector. It was already there but we removed it.
- Do not render unenroll dropdown when the certificate already earned. (I prefer not rendering it just because staff can see the affect while masquerading).
- Make sure the dropdown doesn't show up when no option is available.
Ticket: https://2u-internal.atlassian.net/browse/AU-1232
> fix: stop user from unenroll after earned the certificate

- src/widgets/ProductRecommendations/index.jsx
- src/widgets/ProductRecommendations/index.test.jsx
- src/widgets/ProductRecommendations/testData.js
NB: Widget still hardcoded to not show
- Adjusted the product recommendations widget to display the `NoCoursesView` component if no recommendations is returned from our `product_recommendations` endpoints
- This specific case is if we are dealing with a user who is enrolled in a UT Austin Masters program, in which case, they should not see recommendations
- The placeholder will be displayed in place of our component if the user is enrolled in a course, otherwise, our component will just be hidden since the `NoCoursesView` component is shown by default when the user is not enrolled in anything.
[PTECH-3276](https://jira.2u.com/browse/PTECH-3276)
**View if the user is enrolled in a course, but received no recommendations**
**View if the user is NOT enrolled in a course and received no …
> fix: adjusted footer widget to show placeholder for no recommendations

- src/widgets/ProductRecommendations/optimizely.js
- src/widgets/ProductRecommendations/optimizely.test.js
- Adjusted the creation of the Optimizely client to set the log level to `error` before creating the client, so only logs with a level of `error` are output to the console.
This is because currently, all Optimizely logs are being output to the console, and 1 log in particular includes the currently logged in user's ID, which poses as a potential security issue
[PTECH-3307](https://jira.2u.com/browse/PTECH-3307)
> fix: removed info Optimizely logs

- src/containers/CourseCard/components/CourseCardActions/BeginCourseButton.jsx
- src/containers/CourseCard/components/CourseCardActions/ResumeButton.jsx
- src/containers/CourseCard/components/CourseCardActions/index.jsx
- src/containers/CourseCard/components/CourseCardActions/index.test.jsx
- src/containers/CourseCard/components/CourseCardMenu/__snapshots__/index.test.jsx.snap
- src/containers/CourseCard/components/CourseCardMenu/index.jsx
- src/containers/CourseCard/components/hooks.js
- src/data/constants/course.js
- src/data/redux/app/selectors/courseCard.js
This PR covers the following changes for the B2C side.
Once an ExecEd enrollment has been made, we should
- Hide the ‘Upgrade’ CTA - there is only one enrollment mode for Executive Education courses 
- ‘Begin Course’ and ‘Resume’ CTAs should navigate learners over to their Getsmarter dashboard.
- We will need to ensure that the correct URL and Auth0 org_id parameter are being passed to enable SSO
- Disable additional course options
-  Unenroll, Email Settings, Share on Facebook, and Share on Twitter should all be disabled for ExecEd course cards.
JIRA -> [ENT-7188](https://2u-internal.atlassian.net/browse/ENT-7188)
> feat: frontend changes for executive education courses on B2C dashboard

- src/containers/LearnerDashboardHeader/CollapsedHeader/index.jsx
Fixed collapsed navbar icon 
**Before:**
**After:**
> fix: collapsed navbar icon fix

- src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx
- src/containers/LearnerDashboardHeader/ExpandedHeader/AuthenticatedUserDropdown.jsx
- src/containers/LearnerDashboardHeader/ExpandedHeader/__snapshots__/AuthenticatedUserDropdown.test.jsx.snap
- src/containers/LearnerDashboardHeader/messages.js
[REV-3693](https://2u-internal.atlassian.net/browse/REV-3693).
Modifying the header dropdown back to `Order History` from `Orders & Subscriptions`.
This PR manually reverts https://github.com/openedx/frontend-app-learner-dashboard/pull/164
> feat: Update header user dropdown back to Order History

- plugins/PluginSlot.jsx
* this PR will update the PluggableDashPOC's PluginSlot dummy config in `PluginSlot.jsx` to use the sandbox URL.
> fix: update pluginSlot to use sandbox base URL

- package-lock.json
- package.json
@edx/brand-edx.org package is not open source. @edx/brand-openedx is what is used by other MFEs by default.
Similar PRs:
- [Gradebook](https://github.com/openedx/frontend-app-gradebook/pull/327)
- [ORA grading](https://github.com/openedx/frontend-app-ora-grading/pull/200)
> fix(deps): replace edx.org brand dependency with openedx brand (#183)

- src/widgets/RecommendationsPaintedDoorBtn/PaintedDoorExperimentContext.jsx
There are multiple places where properties of the object provided by `usePaintedDoorExperimentContext()` are assumed to exist. This provides default (null) values for those properties when creating the context.
> fix: default context for painted door experiment

- src/containers/CourseFilterControls/CourseFilterControls.jsx
- src/containers/CourseFilterControls/messages.js
- src/containers/LearnerDashboardHeader/ExpandedHeader/AuthenticatedUserDropdown.jsx
- src/containers/LearnerDashboardHeader/messages.js
resolves https://github.com/openedx/frontend-app-learner-dashboard/issues/217
> fix: replace hardcoded strings and properly define i18n messages

- plugins/PluginSlot.jsx
- src/containers/CourseList/__snapshots__/index.test.jsx.snap
- src/containers/Dashboard/index.jsx
- src/containers/WidgetContainers/NoCoursesSidebar/__snapshots__/index.test.jsx.snap
Combined with [work that got pushed directly to the branch](https://github.com/openedx/frontend-app-learner-dashboard/commit/c3dcf8e0321e822d26a9cafa40a726b036687475) will remove the flickering scrollbars during resize and enable the plugin to take up all available horizontal space (`width: 100%;`)
> fix: scrollbars

- .github/workflows/ci.yml
[APER-3072]
As this service transitions to Aperture for maintainership, we want to ensure that our team receives emails when CI fails in this project.
> chore: add Aperture team OpsGenie email address as a recipient when CI fails for Learner Dashboard

- src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx
- src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx
- src/containers/LearnerDashboardHeader/ExpandedHeader/index.test.jsx
- src/data/services/lms/api.js
- src/data/services/lms/api.test.js
- src/data/services/lms/urls.js
Unenroll URL was picking the stale value of `getConfig().LMS_BASE_URL`. After the following changes, it'll pick the current value of  `getConfig().LMS_BASE_URL`. This is done on the basis of [`openedx/frontend-platform`](https://github.com/openedx/frontend-platform/#:~:text=If%20getConfig%20is%20called%20outside%20of%20a%20component%27s%20render%20lifecycle). This PR will fix the #269 .
> fix: URLs get the current value of LMS_BASE_URL from getConfig() #269

- src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx
- src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx
- src/containers/LearnerDashboardHeader/ExpandedHeader/index.test.jsx
- src/data/services/lms/api.js
- src/data/services/lms/api.test.js
- src/data/services/lms/urls.js
This PR is a backport for https://github.com/openedx/frontend-app-learner-dashboard/pull/273 so unenrollments work in the learner dashboard.
Resolves https://github.com/openedx/wg-build-test-release/issues/336
> fix: URLs get the current value of LMS_BASE_URL from getConfig()

- src/components/ZendeskFab/messages.js
- src/containers/CourseCard/components/CourseCardActions/messages.js
- src/containers/CourseCard/components/CourseCardBanners/CreditBanner/messages.js
- src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/messages.js
- src/containers/CourseCard/components/CourseCardBanners/RelatedProgramsBanner/messages.js
- src/containers/CourseCard/components/CourseCardBanners/messages.js
- src/containers/CourseCard/components/CourseCardDetails/messages.js
- src/containers/CourseCard/components/CourseCardMenu/SocialShareMenu.test.jsx
- src/containers/CourseCard/components/CourseCardMenu/index.test.jsx
- src/containers/CourseCard/components/CourseCardMenu/messages.js
- src/containers/CourseCard/messages.js
- src/containers/EmailSettingsModal/messages.js
- src/containers/RelatedProgramsModal/messages.js
- src/containers/SelectSessionModal/messages.js
- src/containers/UnenrollConfirmModal/components/messages.js
- src/messages.js
This is a fix of #287 . 
It just replace the function used to define messages as explined in the issue, and modifies `*.test` files when/if needed
> fix: #287 translation strigs are not exported

- src/containers/WidgetContainers/LoadedSidebar/__snapshots__/index.test.jsx.snap
- src/containers/WidgetContainers/LoadedSidebar/index.jsx
- src/containers/WidgetContainers/LoadedSidebar/index.test.jsx
- src/containers/WidgetContainers/NoCoursesSidebar/__snapshots__/index.test.jsx.snap
- src/containers/WidgetContainers/NoCoursesSidebar/index.jsx
- src/containers/WidgetContainers/NoCoursesSidebar/index.test.jsx
This PR adds two new plugin slots to the widget sidebar, allowing for optional extensibility.
The recommendations panel will move to being rendered via the frontend plugin framework and the new plugin slots.
> feat!: Removes rendering of the RecommendationsPanel by default in Open edX

- .github/workflows/ci.yml
* Email sent on CI failure  sometimes has an authentication failure.
* A [recent change to action send mail](https://github.com/dawidd6/action-send-mail/commitŋdc13c734ff2b581c12c1b59958ba73d6fa95b371) added debug logging to the action.
* Enabling the debug logging so we can track this down more easily in the future.
AFFECTS: APER-3092
> chore: add logging to the github action

- package-lock.json
- package.json
- src/data/constants/app.js
Upgrades @openedx/paragon to `v22`
This upgrade includes a couple changes to the UI but nothing major.
> chore(deps): upgrade to paragon v22

- src/containers/CourseCard/components/CourseCardBanners/CertificateBanner.jsx
[Jira ticket + context ](https://2u-internal.atlassian.net/browse/ENT-8827)
We have a bug that is present for what we assume to be all learners that are taking an exec ed course that shows that a 50% is needed to pass this course, though no actually passing grade is being sent by any exec ed courses. To combat this, we want to hide this banner for all exec ed.
> fix: hiding certificate banner for exec ed

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/containers/CourseCard/components/CourseCardBanners/CertificateBanner.jsx
[Jira ticket + context](https://2u-internal.atlassian.net/browse/ENT-8827)
We have a bug that is present for what we assume to be all learners that are taking an exec ed course that shows that a 50% is needed to pass this course, though no actually passing grade is being sent by any exec ed courses. To combat this, we want to hide this banner for all exec ed.
This relates to [this PR](https://github.com/openedx/frontend-app-learner-dashboard/pull/326) which was reverted because of a code freeze, but has been validated locally.
> Hiding certificate banner for exec ed courses

- .github/CODEOWNERS
* changing ownership to aperture for this widget  (which is DEPRd  from the open source code base, and aperture is scheduled to remove it at some point).
FIXES: APER-3497
> feat: changing ownership for the recommendations widget

- package-lock.json
- package.json
Similarly to #421, the `axios-mock-adapter` dependency is not being used. Renovate is trying to update this from v1.x to 2.x, this PR removes the dependency instead.
> chore: remove unused dependency -- axios-mock-adapter

- src/App.jsx
- src/__snapshots__/App.test.jsx.snap
[APER-3671](https://2u-internal.atlassian.net/browse/APER-3671)
Contributes to #255
This PR removes the automatic use of the ZendeskFab component from the App level. The ZendeskFab logic still lives in the `src/components` directory.
> feat: remove Zendesk component from App

- .husky/pre-push
- package.json
Update husky usage based on release [notes from v9](https://github.com/typicode/husky/releases/tag/v9.0.1)
`husky install` is deprecated
> fix: update husky

- src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx
- src/containers/LearnerDashboardHeader/__snapshots__/index.test.jsx.snap
- src/containers/LearnerDashboardHeader/hooks.js
- src/containers/LearnerDashboardHeader/hooks.test.js
- src/containers/LearnerDashboardHeader/index.test.jsx
- src/data/services/lms/api.js
- src/data/services/lms/urls.js
- src/hooks/api.js
- src/hooks/api.test.js
This PR removes the link of `programs` from the Header if the service is not configured. 
It aims to solve the following issue https://github.com/openedx/frontend-app-learner-dashboard/issues/372
**How to test**
1. Create a instance with `frontend-app-learner-dashobord` mounted in the current branch.
2. Launch the instance and open it in the browser.
3. Access the learner dashboard.
4. By default you should not see help nav button. 
5. Configure programs service following the instructions here https://github.com/overhangio/tutor-discovery. 
7. Now the tab should be available.
> fix: display programs only if the url is configured

- src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx
- src/containers/LearnerDashboardHeader/__snapshots__/index.test.jsx.snap
- src/containers/LearnerDashboardHeader/hooks.js
- src/containers/LearnerDashboardHeader/hooks.test.js
- src/containers/LearnerDashboardHeader/index.test.jsx
- src/data/services/lms/api.js
- src/data/services/lms/urls.js
- src/hooks/api.js
- src/hooks/api.test.js
This reverts commit e8886c9d9d98f65ec31fe5e7fd7de6c3926c2827.
I'm going to roll this back, it is broken in a live (ie. non-development) environment with real users. The code determines if programs is active by `baseAppUrl('/config/programs');`.  [The URL is permissioned](https://github.com/openedx/django-config-models/blob/32c885d92131fcac1680c518c6f8a127a67f5e2e/config_models/views.py#L42-L52) and is inaccessible  under production circumstances. This will need another method. Possibilities: a URL that's reachable by any logged in user, or a server-side check, or looking to see if this is exposed via a standard config setting. (That last would be ideal.)
The automated tests should also make sure they are using a non-permissioned user, if we have that functionality in jest.
> Revert "fix: display programs only if the url is configured (#479)"

- src/containers/LearnerDashboardHeader/BrandLogo.jsx
- src/containers/LearnerDashboardHeader/BrandLogo.test.jsx
- src/containers/LearnerDashboardHeader/__snapshots__/BrandLogo.test.jsx.snap
This PR includes changes to the `BrandLogo` component in the `LearnerDashboardHeader` to improve its functionality and testing.
**Changes**
- replaced '/' to LMS_BASE_URL if dashboard url does not provided
- updated tests
**Quick demo**
https://github.com/user-attachments/assets/bec02d00-88d4-454d-96e8-1a0e5bdc446b
> fix: added LMS_BASE_URL for brand logo

- package-lock.json
- package.json
We were installing browserslist-config but not declaring it.  This had the effect that webpack - and likely others - were not using it.
> fix: Use browserslist-config

- package-lock.json
- package.json
(This is a backport of #523 to Sumac.)
We were installing browserslist-config but not declaring it.  This had the effect that webpack - and likely others - were not using it.
> fix: Use browserslist-config [Sumac backport]

- src/plugin-slots/CourseCardActionSlot/index.jsx
(This is a Sumac-specific change!)
This removes the upgrade button as default content in CourseCardActionSlot.
This is, for the moment, a Sumac-specific change.  The button is still present in master, pending proper removal (including the component definitions from the rest of the repository) prior to the U release by the maintainers.  See:
https://github.com/openedx/frontend-app-learner-dashboard/issues/438
Before:
After:
> feat: remove upgrade button [Sumac]

- .github/workflows/ci.yml
This action frequently fails, and the current maintainers (@openedx/2U-aperture) don't require it, as we both monitor the success of the workflows and we have individual workflow failure email notifications enabled. After discussion with Axim, we are removing the  action. It can always be added back (and potentially debugged) later if another maintainer would benefit from it.
FIXES: APER-3814
> chore: removing send mail on failure gh action

- src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx
- src/containers/LearnerDashboardHeader/CollapsedHeader/__snapshots__/CollapseMenuBody.test.jsx.snap
- src/containers/LearnerDashboardHeader/ExpandedHeader/__snapshots__/index.test.jsx.snap
- src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx
This PR includes changes to update the URLs in the `LearnerDashboardHeader` components to use the configured LMS base URL instead of hardcoded paths. This ensures that the application correctly redirects to the dashboard in different environments.
https://github.com/user-attachments/assets/6b5e81b7-0f93-44ad-a03b-390a7e847e2b
> fix: fixed module button href

- package.json
This allows development against tutor by running `npm run dev`
Following the pattern from https://github.com/openedx/frontend-app-learning/blob/master/package.json#L22
> chore: add `dev` script to `package.json`

- src/containers/CourseCard/components/CourseCardImage.jsx
- src/containers/CourseCard/components/__snapshots__/CourseCardImage.test.jsx.snap
Closes https://github.com/openedx/frontend-app-learner-dashboard/issues/265.
Course thumbnails on IOS Safari stretch to the full height of the image, instead of being limited by width and preserving aspect ratio. This seems to be a IOS Safari specific behavior[1], and can be fixed by setting height to auto, while width is set to 100%.
This issues is specific to the context of the course card, so we are fixing it by setting the height in the course card css, instead of fixing it globally in the Paragon styles, which wouldn't work in all contexts.
1: https://stackoverflow.com/a/44250830
Screenshots taken from an iPhone of the same course on the course dashboard before and after the fix. Course name censored for privacy.
<details> 
<summary>Before</summary>
</details>
<details> …
> fix: course image height on IOS Safari

- src/plugin-slots/CourseBannerSlot/README.md
Updating docs around the CourseBanner plugin slot to reflect the change to the ID name
> fix: CourseBanner slot readme

- src/containers/CourseCard/components/CourseCardBanners/CourseBanner.jsx
- src/containers/CourseCard/components/CourseCardBanners/CourseBanner.test.jsx
- src/containers/CourseCard/components/CourseCardBanners/__snapshots__/CourseBanner.test.jsx.snap
- src/containers/CourseCard/components/CourseCardBanners/messages.js
This removes references to the upgrade functionality in the `CourseBanner` component. The `CourseBanner` component will render alerts underneath each `CourseCard` to indicate certain states that the enrollment is in. Some of these alerts were referring to the `canUpgrade` boolean from redux store to determine their layout. Any of those alerts that reference upgrades/upgrading an enrollment have been removed in this PR.
> feat: remove upgrade refs course banner

- package-lock.json
- package.json
- src/App.jsx
- src/App.test.jsx
- src/plugin-slots/FooterSlot/README.md
- src/plugin-slots/README.md
https://app.pr-604-550b00.sandboxes.opencraft.hosting/learner-dashboard/
> feat: import `FooterSlot` from component package instead of slot package

- package-lock.json
- package.json
- src/containers/CoursesPanel/hooks.js
- src/containers/CoursesPanel/hooks.test.js
- src/data/services/lms/utils.js
- src/data/services/lms/utils.test.js
- webpack.dev.config.js
- webpack.prod.config.js
We removed the use of `query-string` and replace the use of `stringify` and `stringifyUrl` for our own functions using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), fixed the related tests and deprecate the package.
This PR fixes #571 
The creation of the url in the image (when you hit learner-dashboard) was built using this functions, it removes `user=undefined` from url params so we can get the proper response
> Replace use of query-string dependency for URLSearchParams #571

- src/containers/CoursesPanel/NoCoursesView/__snapshots__/index.test.jsx.snap
- src/containers/CoursesPanel/NoCoursesView/index.jsx
- src/containers/Dashboard/DashboardLayout.jsx
- src/containers/Dashboard/DashboardLayout.test.jsx
- src/containers/Dashboard/__snapshots__/DashboardLayout.test.jsx.snap
- src/containers/Dashboard/index.scss
- src/containers/LearnerDashboardHeader/ConfirmEmailBanner/__snapshots__/index.test.jsx.snap
- src/containers/LearnerDashboardHeader/ConfirmEmailBanner/index.jsx
As part of this PR we fixed:
- Multiple uses of an h1 tag (Files: NoCoursesView, ConfirmEmailBanner)
- h2 being used as a spacer (Files: DashboardLayout), we added a conditional style replicating h2 spacing
| Before | After |
| ----- | ----- |
| <img width="1377" alt="Screenshot 2025-05-12 at 4 44 32 p m" src="https://github.com/user-attachments/assets/4cf2e584-9543-44b9-a71e-0968430d6828" /> | <img width="1624" alt="Screenshot 2025-05-16 at 9 36 19 a m" src="https://github.com/user-attachments/assets/d23cc3d2-932c-406f-868f-b5ca070bfa18" /> |
| <img width="1472" alt="Screenshot 2025-05-12 at 4 45 48 p m" src="https://github.com/user-attachments/assets/732eb9f1-5fa0-49d4-ae5e-1e946929db25" /> | <img width="1469" alt="Screenshot 2025-05-12 at 4 30 27 p m" …
> Audit usage of header elements in Learner Dashboard

- src/containers/LearnerDashboardHeader/ConfirmEmailBanner/index.jsx
- src/data/services/lms/utils.js
The confirm email banner is currently breaking due to a type error that occurs in the `post` utility function. More details on this can be found in the corresponding issue #627 
To fix, we can pass a default empty object as the body for any POST requests that don't contain a body.
> fix: email banner bug

- src/containers/CourseCard/components/CourseCardDetails/hooks.js
- src/data/redux/app/selectors/courseCard.js
- src/data/redux/app/selectors/courseCard.test.js
Currently advertised start date wasn't showing at all on course card or even receiving the value from the endpoints, to accomplish this we had to add that value on the endpoint response and only if a started date was added is showed, if not it falls back to show start date. 
Without advertised start date:
With advertised start date:
This PR fixes #558 
Backend Change: https://github.com/openedx/edx-platform/pull/36726
> Add advertised start date on course card
